name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug info
        run: |
          echo "Current working directory: $(pwd)"
          echo "List directory contents:"
          ls -R
          echo "Docker version:"
          docker --version

      - name: Run the action
        uses: ./  # or ./path/to/action if not at repo root
